### ISSUE TITLE
Question of SDN vs P4

### ISSUE THREAD

**Issue by TKTim** [Princeton-Cabernet/BeauCoup#4]
The program work just fine, but I was wondering why you choose P4 switch?
Is there a necessary need for using P4 switch.

**Comment by chenxiaoqino** [comment]
The current prototype implementation works on high-speed programmable switches. The BeauCoup algorithm should work elsewhere as well, for example on FPGA, SmartNIC, GPUs, etc.

**Comment by TKTim** [comment]
Thx, that helps a lot.
