### ISSUE TITLE
jinja2.exceptions.UndefinedError: dict object has no element 0

### ISSUE THREAD

**Issue by martyer** [Princeton-Cabernet/BeauCoup#5]
How to reproduce:
- Clone repository
- Install dependencies
- Run `python3 py/compiler.py -v --gamma=1.0 query_examples.yaml IR.json` from repository root
- Run `python3 py/p4gen.py -v IR.json p4src/beaucoup.p4template beaucoup.p4`

I pinpointed this issue to the following blocks in the Jinja2 template:
```python
{% for i in range(16) %}
{% if K1 in keydefn[i] %}
  {{i}} : {{A1}}();
{% endif %}
{% if K2 in keydefn[i] %}
  {{i}} : {{A2}}();
{% endif %}
{% endfor %}
```
The template receives the following dictionary as `keydefn` argument, which does not have a "0"-element:
```
{1: ('hdr.ipv4.src_addr',), 2: ('hdr.ipv4.dst_addr', 'hdr.tcp.dst_port'), 3: ('hdr.ipv4.src_addr', 'hdr.ipv4.dst_addr'), 4: ('hdr.ipv4.dst_addr',), 5: ('hdr.ipv4.src_addr', 'hdr.tcp.dst_port'), 6: ('hdr.ipv4.src_addr', 'hdr.udp.dst_port'), 7: ('hdr.ipv4.dst_addr', 'hdr.udp.dst_port'), 8: ('hdr.ipv4.src_addr', 'hdr.ipv4.dst_addr', 'hdr.tcp.src_port'), 9: ('hdr.ipv4.src_addr', 'hdr.ipv4.dst_addr', 'hdr.udp.src_port'), 10: ('hdr.ipv4.src_addr', 'hdr.ipv4.dst_addr', 'hdr.tcp.dst_port'), 11: ('hdr.ipv4.src_addr', 'hdr.ipv4.dst_addr', 'hdr.udp.dst_port'), 12: ('hdr.ipv4.src_addr', 'hdr.ipv4.dst_addr', 'hdr.tcp.src_port', 'hdr.tcp.dst_port')}
```

Am I doing something wrong? Or is there an issue with the template?

**Comment by chenxiaoqino** [comment]
Thanks a lot for reporting the issue. I cannot reproduce it using the latest version of Jinja2 (version 3.0.2) but I understand some version might be more strict when accessing empty dictionary indices. Can you test again using commit 2cc29526 ?

**Comment by martyer** [comment]
Hi, thanks for the quick response.
Commit 2cc29526caa7b6c37da240afa05d0d9375985ded fixed the issue.

Also, I found the original error: Jinja2 version 3.0.1 does not work, but Jinja2 version 3.0.2 works on the commit I originally tried on. The virtualenv I was using already had some packages installed, including an older version of Jinja2 version 3.0.1.
I think stricter version requirements (even fixing the exact version with `==`) in the `requirements.txt` file would possibly prevent such errors in the future.
